package com.example.weather.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Weather entity to be stored in the forageable_database.
 */
// TODO: annotate this data class as an entity with a parameter for the table name
@Entity(tableName = "weather_database")
data class Weather(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val address: String,
    val notes: String?
)
