package com.example.weather.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.weather.domain.WeatherDomainObject

/**
 * Weather entity to be stored in the weather_database.
 */
// TODO: annotate this data class as an entity with a parameter for the table name
@Entity(tableName = "weather_database")
data class WeatherEntity(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val cityName: String,
    val zipCode: String,
    val temp: Double?,
    val imgSrcUrl: String,
    val conditionText: String,
    val windMph: Double,
    val windDirection: String,
    val time: String
)


/**
 * Map weather objects to domain entities
 *
 */
/*
fun List<WeatherEntity>.asDomainModel(): List<WeatherDomainObject> {
    return map {
        WeatherDomainObject(
            location = it.cityName,
            zipcode = it.zipCode,
            tempf = it.temp,
            imgSrcUrl = it.imgSrcUrl,
            conditionText = it.conditionText,
            windMph = it.windMph,
            windDirection = it.windDirection,
            time = it.time

        )
    }


}

     */
